In [ ]:
# Random Forest

# This algorithm utilizes the idea of ensemble techniques - Collection of estimators

# Random Forest is an averaging method whose prediction is function of prediction acheived from 'N' Decision Trees

Algorithm:

1. Data Consists of Rows and Columns
2. A bootstrapped sample is taken (n rows are selected randomly)
3. Random set of features (columns) if we have large no. of features avaialable to us
4. We create as many decision trees as specified by user
5. Final prediction in terms of classification (Majority class/ outcome wins)

In [7]:
# Lets compare a single decision tree against random forest

from sklearn.datasets import load_digits
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [3]:
digits = load_digits()

In [4]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [5]:
X = digits.data
Y = digits.target

In [8]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y, test_size=0.2)

In [15]:
dt = DecisionTreeClassifier(max_depth=7, min_samples_split=4)

In [16]:
dt.fit(xtrain,ytrain)

DecisionTreeClassifier(max_depth=7, min_samples_split=4)

In [17]:
y_pred = dt.predict(xtest)
y_pred

array([9, 7, 1, 8, 1, 4, 6, 8, 9, 4, 5, 3, 1, 7, 1, 5, 1, 1, 7, 6, 4, 9,
       4, 7, 7, 2, 5, 1, 1, 1, 7, 1, 3, 8, 7, 2, 8, 0, 9, 8, 3, 9, 6, 7,
       8, 3, 3, 3, 1, 0, 0, 8, 5, 6, 5, 4, 7, 7, 1, 4, 0, 8, 0, 4, 1, 5,
       0, 1, 7, 9, 7, 5, 3, 5, 6, 3, 5, 2, 3, 6, 5, 5, 5, 8, 1, 0, 6, 4,
       8, 6, 1, 4, 9, 5, 4, 1, 7, 4, 2, 0, 9, 7, 0, 9, 5, 2, 3, 9, 1, 1,
       7, 2, 7, 6, 7, 0, 0, 7, 1, 1, 8, 4, 4, 8, 4, 5, 2, 2, 6, 7, 0, 3,
       9, 4, 4, 1, 3, 3, 3, 4, 0, 1, 9, 9, 3, 6, 3, 4, 5, 7, 7, 9, 6, 2,
       8, 4, 1, 7, 1, 2, 5, 9, 6, 2, 2, 0, 6, 2, 6, 0, 9, 5, 0, 7, 0, 4,
       5, 8, 6, 8, 6, 7, 2, 1, 0, 6, 7, 2, 1, 9, 6, 0, 1, 9, 9, 6, 8, 0,
       2, 1, 6, 1, 4, 9, 0, 5, 5, 7, 1, 9, 9, 8, 8, 8, 5, 4, 7, 9, 0, 6,
       2, 1, 1, 6, 4, 7, 3, 6, 8, 3, 5, 0, 9, 3, 1, 3, 7, 9, 8, 9, 5, 7,
       7, 2, 9, 8, 2, 9, 6, 4, 1, 6, 0, 1, 7, 4, 4, 8, 8, 0, 4, 7, 3, 2,
       9, 0, 0, 7, 5, 0, 1, 3, 5, 3, 9, 4, 8, 9, 6, 7, 7, 7, 5, 6, 7, 3,
       6, 7, 7, 6, 9, 3, 8, 1, 8, 4, 2, 3, 1, 0, 8,

In [18]:
dt.score(xtest, ytest)

0.7888888888888889

In [19]:
dt.score(xtrain, ytrain)

0.8830897703549061

In [ ]:
# We could try hper parameter training. But that doesn't works usuallyRandom Forest would be useful 

In [20]:
rf = RandomForestClassifier(n_estimators=250, max_features=0.5, bootstrap=True, max_samples=0.6, n_jobs = -1)

In [21]:
rf.fit(xtrain, ytrain)

RandomForestClassifier(max_features=0.5, max_samples=0.6, n_estimators=250,
                       n_jobs=-1)

In [22]:
rf.score(xtest, ytest)

0.975

In [23]:
rf.score(xtrain, ytrain)

1.0

In [25]:
y_pred = rf.predict(xtest)
y_pred

array([1, 7, 1, 8, 2, 4, 6, 8, 9, 4, 5, 3, 8, 7, 9, 5, 1, 1, 7, 2, 4, 9,
       4, 7, 7, 2, 5, 1, 7, 1, 7, 1, 5, 4, 7, 2, 8, 0, 9, 3, 3, 9, 6, 9,
       8, 4, 4, 3, 1, 0, 0, 2, 4, 6, 0, 4, 7, 7, 1, 1, 0, 8, 0, 4, 1, 6,
       0, 2, 7, 3, 4, 5, 3, 5, 6, 3, 5, 2, 5, 6, 5, 0, 5, 8, 1, 0, 6, 4,
       8, 6, 1, 4, 9, 5, 4, 2, 9, 4, 2, 0, 9, 7, 0, 9, 5, 9, 3, 9, 1, 1,
       7, 2, 7, 6, 7, 0, 0, 7, 1, 8, 8, 7, 4, 8, 4, 5, 2, 9, 6, 8, 0, 3,
       9, 4, 4, 1, 3, 3, 3, 4, 0, 1, 9, 1, 3, 6, 6, 4, 4, 7, 7, 9, 6, 2,
       8, 4, 8, 8, 1, 2, 5, 9, 6, 2, 2, 0, 5, 2, 6, 0, 9, 5, 0, 7, 0, 4,
       5, 8, 6, 8, 6, 9, 2, 2, 0, 6, 7, 2, 2, 9, 6, 0, 1, 9, 3, 6, 9, 0,
       2, 8, 6, 1, 4, 9, 0, 5, 5, 7, 1, 4, 9, 9, 8, 8, 5, 4, 7, 9, 0, 6,
       8, 1, 8, 6, 4, 7, 6, 6, 8, 3, 5, 0, 9, 3, 1, 3, 7, 9, 8, 9, 5, 4,
       7, 2, 9, 8, 4, 9, 6, 4, 2, 6, 0, 1, 7, 4, 4, 8, 7, 0, 4, 4, 3, 2,
       9, 0, 0, 7, 5, 0, 1, 3, 5, 3, 9, 4, 1, 9, 6, 7, 7, 7, 6, 4, 8, 3,
       6, 7, 7, 6, 9, 3, 8, 2, 2, 4, 2, 3, 7, 0, 9,

In [26]:
from sklearn.metrics import classification_report
print(classification_report(ytest, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.97      1.00      0.98        32
           2       1.00      1.00      1.00        31
           3       1.00      0.88      0.93        32
           4       0.98      0.98      0.98        50
           5       0.97      0.90      0.93        31
           6       1.00      0.97      0.99        38
           7       0.95      1.00      0.98        42
           8       0.97      1.00      0.98        31
           9       0.93      1.00      0.96        37

    accuracy                           0.97       360
   macro avg       0.98      0.97      0.97       360
weighted avg       0.98      0.97      0.97       360



In [27]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ytest, y_pred))

[[36  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  0  0  0]
 [ 0  0 31  0  0  0  0  0  0  0]
 [ 0  0  0 28  0  0  0  2  1  1]
 [ 0  0  0  0 49  1  0  0  0  0]
 [ 0  0  0  0  1 28  0  0  0  2]
 [ 0  1  0  0  0  0 37  0  0  0]
 [ 0  0  0  0  0  0  0 42  0  0]
 [ 0  0  0  0  0  0  0  0 31  0]
 [ 0  0  0  0  0  0  0  0  0 37]]


In [28]:
rf.feature_importances_

array([0.00000000e+00, 1.59722971e-03, 1.29321328e-02, 7.07549071e-03,
       7.22551505e-03, 3.45390476e-02, 4.12300373e-03, 4.46030779e-04,
       9.47570887e-05, 7.13065151e-03, 2.56759248e-02, 3.42035510e-03,
       1.46792559e-02, 1.84571914e-02, 2.65070429e-03, 3.17858425e-04,
       2.56582923e-05, 4.76965115e-03, 1.58648460e-02, 3.02971070e-02,
       3.28158638e-02, 7.77697629e-02, 4.15601849e-03, 4.37101725e-04,
       1.91581742e-05, 7.40582077e-03, 5.67798634e-02, 3.16469505e-02,
       4.45705986e-02, 2.03643465e-02, 1.99256411e-02, 1.00714436e-05,
       0.00000000e+00, 3.90804736e-02, 2.32026232e-02, 1.09489978e-02,
       5.56893637e-02, 1.41138442e-02, 2.50278213e-02, 0.00000000e+00,
       1.01368093e-05, 4.31912927e-03, 5.10683340e-02, 5.68339899e-02,
       1.65714147e-02, 1.85698882e-02, 1.61490071e-02, 6.19805744e-05,
       0.00000000e+00, 1.20523871e-03, 1.12543606e-02, 1.44218915e-02,
       8.19540589e-03, 1.79712736e-02, 3.05219222e-02, 1.22859047e-03,
      