In [1]:
import numpy as np

In [32]:
arr = np.random.rand(2,3)
arr

array([[0.52768862, 0.63339978, 0.67312028],
       [0.35678879, 0.15282685, 0.07788761]])

In [33]:
np.log(arr) # log base 10

array([[-0.6392489 , -0.4566535 , -0.39583124],
       [-1.03061128, -1.8784497 , -2.55248836]])

In [34]:
np.log2(arr) # # log base 2

array([[-0.92224122, -0.65881173, -0.57106377],
       [-1.48685779, -2.71003007, -3.68246229]])

In [35]:
np.cumsum(arr)

array([0.52768862, 1.1610884 , 1.83420868, 2.19099748, 2.34382433,
       2.42171194])

In [36]:
np.sum(arr, axis=0)

array([0.88447742, 0.78622663, 0.75100789])

In [37]:
np.sum(arr, axis=1)

array([1.83420868, 0.58750326])

In [21]:
arr = np.random.randint(0,100,20)
arr

array([25, 29, 24, 20, 73, 55, 64, 19, 88, 40, 42, 12, 39, 25, 80, 62, 95,
       81, 77, 28])

In [22]:
arr[5:10]

array([55, 64, 19, 88, 40])

In [23]:
arr[2:20:2]

array([24, 73, 64, 88, 42, 39, 80, 95, 77])

In [24]:
arr[-4:-18:-2]

array([95, 80, 39, 42, 88, 64, 73])

In [25]:
arr[::-1]

array([28, 77, 81, 95, 62, 80, 25, 39, 12, 42, 40, 88, 19, 64, 55, 73, 20,
       24, 29, 25])

In [30]:
arr[4:-1:-1]

array([], dtype=int32)

In [38]:
np.pi

3.141592653589793

In [39]:
np.e


2.718281828459045

In [40]:
#matrix

A= np.array([[1,1],[0,1]])
B= np.array([[2,0],[3,4]])

print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [41]:
#elementwise matrix multiplication. Hamadard product

print("Elementwise")
print(A*B)

#matrix multiplication

print ("matrix product")
print(A@B)

#alternatively

print(A.dot(B))

Elementwise
[[2 0]
 [0 4]]
matrix product
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [53]:
# write prog to implement Y=AX+C in numpy

A = np.random.randint(1,20,(2,3))
C = np.random.randint(1,20,(2,3))
print(A)
print(C)

X= np.ones((3,3))
print(X)

Y= ((A@X) + C ) 
print(Y)

[[ 3 19 12]
 [19 12 17]]
[[ 9 10  6]
 [ 2  7 18]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[43. 44. 40.]
 [50. 55. 66.]]


In [54]:
A.ravel() #converts to 1-d array
A

array([[ 3, 19, 12],
       [19, 12, 17]])

In [57]:
A=A.reshape(5,2)
A

ValueError: cannot reshape array of size 6 into shape (5,2)

In [56]:
A.T  # transpose

array([[ 3, 19],
       [19, 12],
       [12, 17]])

In [58]:
#Stack different arrays together
A= np.floor(10*np.random.random((2,3)))
A

array([[3., 0., 5.],
       [6., 9., 1.]])

In [59]:
B= np.ceil(10*np.random.random((2,3)))
B

array([[3., 7., 8.],
       [4., 1., 8.]])

In [60]:
#vertical stacking - should have same number of columns
np.vstack((A,B))

array([[3., 0., 5.],
       [6., 9., 1.],
       [3., 7., 8.],
       [4., 1., 8.]])

In [61]:
#horizontal stacking - should have same number of rows
np.hstack((A,B))

array([[3., 0., 5., 3., 7., 8.],
       [6., 9., 1., 4., 1., 8.]])

In [62]:
#splitting arrays
a= np.ceil(10*np.random.random((3,12)))
a


array([[ 5.,  8.,  1.,  2., 10.,  7.,  8.,  5.,  8.,  2.,  3.,  4.],
       [ 3.,  6.,  8.,  3.,  8.,  7.,  4.,  3.,  7.,  7.,  2., 10.],
       [ 3.,  2.,  8.,  3.,  7.,  9.,  4.,  1.,  1.,  9.,  6.,  6.]])

In [63]:
np.hsplit(a,3)

[array([[5., 8., 1., 2.],
        [3., 6., 8., 3.],
        [3., 2., 8., 3.]]),
 array([[10.,  7.,  8.,  5.],
        [ 8.,  7.,  4.,  3.],
        [ 7.,  9.,  4.,  1.]]),
 array([[ 8.,  2.,  3.,  4.],
        [ 7.,  7.,  2., 10.],
        [ 1.,  9.,  6.,  6.]])]

In [64]:
np.vsplit(a,3)

[array([[ 5.,  8.,  1.,  2., 10.,  7.,  8.,  5.,  8.,  2.,  3.,  4.]]),
 array([[ 3.,  6.,  8.,  3.,  8.,  7.,  4.,  3.,  7.,  7.,  2., 10.]]),
 array([[3., 2., 8., 3., 7., 9., 4., 1., 1., 9., 6., 6.]])]

In [75]:
# numpy array is blazingly faster than python lists

import math
import time

size_vector = 10000000

def pure_python_version():
    t1=time.time()
    X = range(size_vector)
    Y = range(size_vector)
    Z = [X[i] * Y[i] for i in range(len(X))]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_vector)
    Y = np.arange(size_vector)
    Z = X*Y
    return time.time() -t1

t1 = pure_python_version()
t2 = numpy_version()

print(t1, "\t", t2)
print ("Numpy in this example is: " + str(math.floor(t1/t2)) + "x faster")

2.686295986175537 	 0.04089164733886719
Numpy in this example is: 65x faster


In [3]:
import numpy as np

# 1. find the most frequent number in numpy array


In [76]:
arr = np.random.randint(4,30,20)

In [77]:
arr

array([26, 20, 24, 17, 29, 19, 15, 27, 24, 21, 27,  8, 14, 12, 17, 20, 18,
       15, 15, 25])

In [78]:
val , count  = np.unique(arr, return_counts = True)
val


array([ 8, 12, 14, 15, 17, 18, 19, 20, 21, 24, 25, 26, 27, 29])

In [79]:
count

array([1, 1, 1, 3, 2, 1, 1, 2, 1, 2, 1, 1, 2, 1], dtype=int64)

In [80]:
print(val[np.argmax(count)])

15


# 2. Top 5 maximum values and their indices in array

In [81]:
sort_arr= np.sort(arr)
sort_arr

array([ 8, 12, 14, 15, 15, 15, 17, 17, 18, 19, 20, 20, 21, 24, 24, 25, 26,
       27, 27, 29])

In [82]:
sliced_arr = sort_arr[::-5]
sliced_arr

array([29, 24, 19, 15])

In [97]:
sliced_arr = sort_arr[::-5]
for i in (sliced_arr):
    indx = np.where(arr == i)
    print ("The element", i, "is present at index ", indx[0] )

The element 29 is present at index  [4]
The element 24 is present at index  [2 8]
The element 19 is present at index  [5]
The element 15 is present at index  [ 6 17 18]


# 3.  Euclidean distance between 2 numpy arrays

In [87]:
arr1 = np.random.randint(1,30,3)
arr2 = np.random.randint(1,30,3)
arr1


array([11, 28, 22])

In [88]:
arr2

array([4, 5, 6])

In [89]:
temp = arr1 - arr2
 
sum_sq = np.dot(temp.T, temp)
print("The Euclidean distance of the two arrays is",np.sqrt(sum_sq))

The Euclidean distance of the two arrays is 28.879058156387302


# 4.  Find Duplicate values in an numpy array


In [90]:

arr3 = np.random.randint(4,30,20)
arr3


array([22, 23, 26,  6, 25, 25, 18, 13, 13, 29, 23, 23, 23,  5, 22, 25, 15,
       16,  7,  8])

In [91]:
val , count  = np.unique(arr3, return_counts = True)
val

array([ 5,  6,  7,  8, 13, 15, 16, 18, 22, 23, 25, 26, 29])

In [92]:
count

array([1, 1, 1, 1, 2, 1, 1, 1, 2, 4, 3, 1, 1], dtype=int64)

In [93]:
print("The duplicate elements are: ")
for i in range(0, len(count)-1):
    if count[i]>1:
        print(val[i])

The duplicate elements are: 
13
22
23
25


# 5. Find common elements between two numpy arrays 

In [94]:

arr4 = np.random.randint(1,30,20)
arr5 = np.random.randint(1,30,20)
arr4

array([12,  5, 12, 12, 21, 27, 26, 13, 12,  3,  1,  4, 10, 18, 27,  6, 26,
       14, 14, 12])

In [95]:
arr5

array([27, 12, 19,  7, 27,  6, 29,  5, 29,  3, 13,  9,  6, 12, 25,  5, 26,
        2, 22, 26])

In [96]:
print("The common elements between two numpy arrays are:\n", np.intersect1d(arr4, arr5))

The common elements between two numpy arrays are:
 [ 3  5  6 12 13 26 27]
